version: 2

sources:
  - name: zoom_raw
    schema: ZOOM_RAW_SCHEMA
    description: "Raw data from Zoom platform"
    tables:
      - name: users
        description: "Raw user data from Zoom platform"
        columns:
          - name: email
            description: "User email address"
          - name: user_name
            description: "User display name"
          - name: plan_type
            description: "User subscription plan type"
          - name: company
            description: "User company name"
          - name: user_id
            description: "Unique user identifier"
          - name: source_system
            description: "Source system identifier"
          - name: load_timestamp
            description: "Data load timestamp"
          - name: update_timestamp
            description: "Data update timestamp"
      
      - name: meetings
        description: "Raw meeting data from Zoom platform"
        columns:
          - name: meeting_topic
            description: "Meeting topic or title"
          - name: duration_minutes
            description: "Meeting duration in minutes"
          - name: end_time
            description: "Meeting end time"
          - name: start_time
            description: "Meeting start time"
          - name: meeting_id
            description: "Unique meeting identifier"
          - name: host_id
            description: "Meeting host identifier"
          - name: source_system
            description: "Source system identifier"
          - name: load_timestamp
            description: "Data load timestamp"
          - name: update_timestamp
            description: "Data update timestamp"
      
      - name: licenses
        description: "Raw license data from Zoom platform"
        columns:
          - name: license_type
            description: "Type of license"
          - name: end_date
            description: "License end date"
          - name: start_date
            description: "License start date"
          - name: license_id
            description: "Unique license identifier"
          - name: assigned_to_user_id
            description: "User ID assigned to license"
          - name: source_system
            description: "Source system identifier"
          - name: load_timestamp
            description: "Data load timestamp"
          - name: update_timestamp
            description: "Data update timestamp"
      
      - name: support_tickets
        description: "Raw support ticket data from Zoom platform"
        columns:
          - name: resolution_status
            description: "Ticket resolution status"
          - name: open_date
            description: "Ticket open date"
          - name: ticket_type
            description: "Type of support ticket"
          - name: ticket_id
            description: "Unique ticket identifier"
          - name: user_id
            description: "User ID associated with ticket"
          - name: source_system
            description: "Source system identifier"
          - name: load_timestamp
            description: "Data load timestamp"
          - name: update_timestamp
            description: "Data update timestamp"
      
      - name: billing_events
        description: "Raw billing event data from Zoom platform"
        columns:
          - name: amount
            description: "Billing amount"
          - name: event_type
            description: "Type of billing event"
          - name: event_date
            description: "Date of billing event"
          - name: event_id
            description: "Unique event identifier"
          - name: user_id
            description: "User ID associated with billing event"
          - name: source_system
            description: "Source system identifier"
          - name: load_timestamp
            description: "Data load timestamp"
          - name: update_timestamp
            description: "Data update timestamp"
      
      - name: participants
        description: "Raw participant data from Zoom platform"
        columns:
          - name: leave_time
            description: "Participant leave time"
          - name: join_time
            description: "Participant join time"
          - name: participant_id
            description: "Unique participant identifier"
          - name: meeting_id
            description: "Meeting ID for participant"
          - name: user_id
            description: "User ID of participant"
          - name: source_system
            description: "Source system identifier"
          - name: load_timestamp
            description: "Data load timestamp"
          - name: update_timestamp
            description: "Data update timestamp"
      
      - name: webinars
        description: "Raw webinar data from Zoom platform"
        columns:
          - name: end_time
            description: "Webinar end time"
          - name: webinar_topic
            description: "Webinar topic or title"
          - name: start_time
            description: "Webinar start time"
          - name: registrants
            description: "Number of webinar registrants"
          - name: webinar_id
            description: "Unique webinar identifier"
          - name: host_id
            description: "Webinar host identifier"
          - name: source_system
            description: "Source system identifier"
          - name: load_timestamp
            description: "Data load timestamp"
          - name: update_timestamp
            description: "Data update timestamp"
      
      - name: feature_usage
        description: "Raw feature usage data from Zoom platform"
        columns:
          - name: feature_name
            description: "Name of the feature used"
          - name: usage_date
            description: "Date of feature usage"
          - name: usage_count
            description: "Count of feature usage"
          - name: usage_id
            description: "Unique usage identifier"
          - name: meeting_id
            description: "Meeting ID associated with usage"
          - name: source_system
            description: "Source system identifier"
          - name: load_timestamp
            description: "Data load timestamp"
          - name: update_timestamp
            description: "Data update timestamp"

models:
  - name: bz_audit_log
    description: "Bronze layer audit log for tracking data processing operations"
    columns:
      - name: record_id
        description: "Auto-incrementing unique identifier for each audit record"
      - name: source_table
        description: "Name of the source table being processed"
      - name: load_timestamp
        description: "Timestamp when the data processing operation occurred"
      - name: processed_by
        description: "Identifier of the process or user that performed the operation"
      - name: processing_time
        description: "Time taken to complete the processing operation in milliseconds"
      - name: status
        description: "Status of the processing operation (SUCCESS, FAILED, WARNING)"
  
  - name: bz_users
    description: "Bronze layer user data with audit information"
    columns:
      - name: email
        description: "User primary email address for authentication and communication"
      - name: user_name
        description: "Display name of the user"
      - name: plan_type
        description: "Subscription plan type (Basic, Pro, Business, Enterprise)"
      - name: company
        description: "Company or organization name"
      - name: user_id
        description: "Unique user identifier"
      - name: load_timestamp
        description: "Timestamp when the record was loaded into bronze layer"
      - name: update_timestamp
        description: "Timestamp when the record was last updated"
      - name: source_system
        description: "Source system identifier (e.g., ZOOM_RAW_SCHEMA)"
  
  - name: bz_meetings
    description: "Bronze layer meeting data with audit information"
    columns:
      - name: meeting_topic
        description: "Subject or descriptive title of the meeting"
      - name: duration_minutes
        description: "Total meeting duration in minutes"
      - name: end_time
        description: "Meeting end timestamp"
      - name: start_time
        description: "Meeting start timestamp"
      - name: meeting_id
        description: "Unique meeting identifier"
      - name: host_id
        description: "Meeting host identifier"
      - name: load_timestamp
        description: "Timestamp when the record was loaded into bronze layer"
      - name: update_timestamp
        description: "Timestamp when the record was last updated"
      - name: source_system
        description: "Source system identifier (e.g., ZOOM_RAW_SCHEMA)"
  
  - name: bz_licenses
    description: "Bronze layer license data with audit information"
    columns:
      - name: license_type
        description: "Type or category of the license (Basic, Pro, Enterprise)"
      - name: end_date
        description: "License expiration date"
      - name: start_date
        description: "License activation date"
      - name: license_id
        description: "Unique license identifier"
      - name: assigned_to_user_id
        description: "User ID assigned to license"
      - name: load_timestamp
        description: "Timestamp when the record was loaded into bronze layer"
      - name: update_timestamp
        description: "Timestamp when the record was last updated"
      - name: source_system
        description: "Source system identifier (e.g., ZOOM_RAW_SCHEMA)"
  
  - name: bz_support_tickets
    description: "Bronze layer support ticket data with audit information"
    columns:
      - name: resolution_status
        description: "Current status of the support ticket (Open, In Progress, Resolved, Closed)"
      - name: open_date
        description: "Date when the support ticket was opened"
      - name: ticket_type
        description: "Category or type of the support ticket (Technical, Billing, General)"
      - name: ticket_id
        description: "Unique ticket identifier"
      - name: user_id
        description: "User ID associated with ticket"
      - name: load_timestamp
        description: "Timestamp when the record was loaded into bronze layer"
      - name: update_timestamp
        description: "Timestamp when the record was last updated"
      - name: source_system
        description: "Source system identifier (e.g., ZOOM_RAW_SCHEMA)"
  
  - name: bz_billing_events
    description: "Bronze layer billing event data with audit information"
    columns:
      - name: amount
        description: "Monetary amount associated with the billing event"
      - name: event_type
        description: "Type of billing event (Charge, Refund, Credit, Payment)"
      - name: event_date
        description: "Date when the billing event occurred"
      - name: event_id
        description: "Unique event identifier"
      - name: user_id
        description: "User ID associated with billing event"
      - name: load_timestamp
        description: "Timestamp when the record was loaded into bronze layer"
      - name: update_timestamp
        description: "Timestamp when the record was last updated"
      - name: source_system
        description: "Source system identifier (e.g., ZOOM_RAW_SCHEMA)"
  
  - name: bz_participants
    description: "Bronze layer participant data with audit information"
    columns:
      - name: leave_time
        description: "Timestamp when the participant left the meeting or webinar"
      - name: join_time
        description: "Timestamp when the participant joined the meeting or webinar"
      - name: participant_id
        description: "Unique participant identifier"
      - name: meeting_id
        description: "Meeting ID for participant"
      - name: user_id
        description: "User ID of participant"
      - name: load_timestamp
        description: "Timestamp when the record was loaded into bronze layer"
      - name: update_timestamp
        description: "Timestamp when the record was last updated"
      - name: source_system
        description: "Source system identifier (e.g., ZOOM_RAW_SCHEMA)"
  
  - name: bz_webinars
    description: "Bronze layer webinar data with audit information"
    columns:
      - name: end_time
        description: "Webinar end timestamp"
      - name: webinar_topic
        description: "Subject or descriptive title of the webinar"
      - name: start_time
        description: "Webinar start timestamp"
      - name: registrants
        description: "Number of registered participants for the webinar"
      - name: webinar_id
        description: "Unique webinar identifier"
      - name: host_id
        description: "Webinar host identifier"
      - name: load_timestamp
        description: "Timestamp when the record was loaded into bronze layer"
      - name: update_timestamp
        description: "Timestamp when the record was last updated"
      - name: source_system
        description: "Source system identifier (e.g., ZOOM_RAW_SCHEMA)"
  
  - name: bz_feature_usage
    description: "Bronze layer feature usage data with audit information"
    columns:
      - name: feature_name
        description: "Name of the platform feature being tracked (Screen Share, Recording, Chat, Breakout Rooms)"
      - name: usage_date
        description: "Date when the feature was used"
      - name: usage_count
        description: "Number of times the feature was used during the specified date"
      - name: usage_id
        description: "Unique usage identifier"
      - name: meeting_id
        description: "Meeting ID associated with usage"
      - name: load_timestamp
        description: "Timestamp when the record was loaded into bronze layer"
      - name: update_timestamp
        description: "Timestamp when the record was last updated"
      - name: source_system
        description: "Source system identifier (e.g., ZOOM_RAW_SCHEMA)"
