version: 2

# Source definitions for raw data tables
sources:
  - name: zoom_raw
    description: "Raw data from Zoom platform ingested into ZOOM_RAW_SCHEMA"
    database: ZOOM_DATABASE
    schema: ZOOM_RAW_SCHEMA
    tables:
      - name: MEETINGS
        description: "Raw meetings data from Zoom platform"
        columns:
          - name: MEETING_ID
            description: "Unique identifier for the meeting"
          - name: MEETING_TOPIC
            description: "Topic or title of the meeting"
          - name: HOST_ID
            description: "Identifier of the meeting host"
          - name: START_TIME
            description: "Meeting start timestamp"
          - name: END_TIME
            description: "Meeting end timestamp"
          - name: DURATION_MINUTES
            description: "Meeting duration in minutes"
          - name: LOAD_TIMESTAMP
            description: "Timestamp when record was loaded"
          - name: UPDATE_TIMESTAMP
            description: "Timestamp when record was last updated"
          - name: SOURCE_SYSTEM
            description: "Source system identifier"

      - name: LICENSES
        description: "Raw license data from Zoom platform"
        columns:
          - name: LICENSE_ID
            description: "Unique identifier for the license"
          - name: LICENSE_TYPE
            description: "Type of Zoom license"
          - name: ASSIGNED_TO_USER_ID
            description: "User ID to whom license is assigned"
          - name: START_DATE
            description: "License start date"
          - name: END_DATE
            description: "License end date"
          - name: LOAD_TIMESTAMP
            description: "Timestamp when record was loaded"
          - name: UPDATE_TIMESTAMP
            description: "Timestamp when record was last updated"
          - name: SOURCE_SYSTEM
            description: "Source system identifier"

      - name: SUPPORT_TICKETS
        description: "Raw support ticket data from Zoom platform"
        columns:
          - name: TICKET_ID
            description: "Unique identifier for the support ticket"
          - name: USER_ID
            description: "User ID who created the ticket"
          - name: TICKET_TYPE
            description: "Type of support ticket"
          - name: RESOLUTION_STATUS
            description: "Current status of ticket resolution"
          - name: OPEN_DATE
            description: "Date when ticket was opened"
          - name: LOAD_TIMESTAMP
            description: "Timestamp when record was loaded"
          - name: UPDATE_TIMESTAMP
            description: "Timestamp when record was last updated"
          - name: SOURCE_SYSTEM
            description: "Source system identifier"

      - name: USERS
        description: "Raw user data from Zoom platform"
        columns:
          - name: USER_ID
            description: "Unique identifier for the user"
          - name: USER_NAME
            description: "Display name of the user"
          - name: EMAIL
            description: "Email address of the user"
          - name: COMPANY
            description: "Company name of the user"
          - name: PLAN_TYPE
            description: "Zoom plan type for the user"
          - name: LOAD_TIMESTAMP
            description: "Timestamp when record was loaded"
          - name: UPDATE_TIMESTAMP
            description: "Timestamp when record was last updated"
          - name: SOURCE_SYSTEM
            description: "Source system identifier"

      - name: BILLING_EVENTS
        description: "Raw billing events data from Zoom platform"
        columns:
          - name: EVENT_ID
            description: "Unique identifier for the billing event"
          - name: USER_ID
            description: "User ID associated with the billing event"
          - name: EVENT_TYPE
            description: "Type of billing event"
          - name: EVENT_DATE
            description: "Date of the billing event"
          - name: AMOUNT
            description: "Amount associated with the billing event"
          - name: LOAD_TIMESTAMP
            description: "Timestamp when record was loaded"
          - name: UPDATE_TIMESTAMP
            description: "Timestamp when record was last updated"
          - name: SOURCE_SYSTEM
            description: "Source system identifier"

      - name: PARTICIPANTS
        description: "Raw participant data from Zoom platform"
        columns:
          - name: PARTICIPANT_ID
            description: "Unique identifier for the participant"
          - name: MEETING_ID
            description: "Meeting ID the participant joined"
          - name: USER_ID
            description: "User ID of the participant"
          - name: JOIN_TIME
            description: "Timestamp when participant joined"
          - name: LEAVE_TIME
            description: "Timestamp when participant left"
          - name: LOAD_TIMESTAMP
            description: "Timestamp when record was loaded"
          - name: UPDATE_TIMESTAMP
            description: "Timestamp when record was last updated"
          - name: SOURCE_SYSTEM
            description: "Source system identifier"

      - name: WEBINARS
        description: "Raw webinar data from Zoom platform"
        columns:
          - name: WEBINAR_ID
            description: "Unique identifier for the webinar"
          - name: WEBINAR_TOPIC
            description: "Topic or title of the webinar"
          - name: HOST_ID
            description: "Identifier of the webinar host"
          - name: START_TIME
            description: "Webinar start timestamp"
          - name: END_TIME
            description: "Webinar end timestamp"
          - name: REGISTRANTS
            description: "Number of webinar registrants"
          - name: LOAD_TIMESTAMP
            description: "Timestamp when record was loaded"
          - name: UPDATE_TIMESTAMP
            description: "Timestamp when record was last updated"
          - name: SOURCE_SYSTEM
            description: "Source system identifier"

      - name: FEATURE_USAGE
        description: "Raw feature usage data from Zoom platform"
        columns:
          - name: USAGE_ID
            description: "Unique identifier for the usage record"
          - name: MEETING_ID
            description: "Meeting ID where feature was used"
          - name: FEATURE_NAME
            description: "Name of the feature used"
          - name: USAGE_DATE
            description: "Date when feature was used"
          - name: USAGE_COUNT
            description: "Count of feature usage"
          - name: LOAD_TIMESTAMP
            description: "Timestamp when record was loaded"
          - name: UPDATE_TIMESTAMP
            description: "Timestamp when record was last updated"
          - name: SOURCE_SYSTEM
            description: "Source system identifier"

# Model definitions for bronze layer tables
models:
  - name: bz_audit_log
    description: "Bronze layer audit log for tracking data processing activities"
    columns:
      - name: source_table
        description: "Name of the source table being processed"
        data_type: varchar(255)
      - name: process_start_time
        description: "Timestamp when processing started"
        data_type: timestamp_ntz
      - name: process_end_time
        description: "Timestamp when processing ended"
        data_type: timestamp_ntz
      - name: process_status
        description: "Status of the processing (STARTED, COMPLETED, FAILED)"
        data_type: varchar(50)
      - name: processed_by
        description: "System or user that processed the data"
        data_type: varchar(255)
      - name: records_processed
        description: "Number of records processed"
        data_type: number
      - name: error_message
        description: "Error message if processing failed"
        data_type: varchar(1000)
      - name: created_at
        description: "Timestamp when audit record was created"
        data_type: timestamp_ntz

  - name: bz_meetings
    description: "Bronze layer meetings data with data quality checks"
    columns:
      - name: MEETING_ID
        description: "Unique identifier for the meeting"
        data_type: varchar
      - name: MEETING_TOPIC
        description: "Topic or title of the meeting"
        data_type: varchar
      - name: HOST_ID
        description: "Identifier of the meeting host"
        data_type: varchar
      - name: START_TIME
        description: "Meeting start timestamp"
        data_type: timestamp_ntz
      - name: END_TIME
        description: "Meeting end timestamp"
        data_type: timestamp_ntz
      - name: DURATION_MINUTES
        description: "Meeting duration in minutes"
        data_type: number
      - name: LOAD_TIMESTAMP
        description: "Timestamp when record was loaded from source"
        data_type: timestamp_ntz
      - name: UPDATE_TIMESTAMP
        description: "Timestamp when record was last updated in source"
        data_type: timestamp_ntz
      - name: SOURCE_SYSTEM
        description: "Source system identifier"
        data_type: varchar
      - name: bronze_created_at
        description: "Timestamp when record was created in bronze layer"
        data_type: timestamp_ntz
      - name: bronze_updated_at
        description: "Timestamp when record was last updated in bronze layer"
        data_type: timestamp_ntz
      - name: data_quality_status
        description: "Data quality validation status"
        data_type: varchar

  - name: bz_licenses
    description: "Bronze layer licenses data with data quality checks"
    columns:
      - name: LICENSE_ID
        description: "Unique identifier for the license"
        data_type: varchar
      - name: LICENSE_TYPE
        description: "Type of Zoom license"
        data_type: varchar
      - name: ASSIGNED_TO_USER_ID
        description: "User ID to whom license is assigned"
        data_type: varchar
      - name: START_DATE
        description: "License start date"
        data_type: date
      - name: END_DATE
        description: "License end date"
        data_type: date
      - name: LOAD_TIMESTAMP
        description: "Timestamp when record was loaded from source"
        data_type: timestamp_ntz
      - name: UPDATE_TIMESTAMP
        description: "Timestamp when record was last updated in source"
        data_type: timestamp_ntz
      - name: SOURCE_SYSTEM
        description: "Source system identifier"
        data_type: varchar
      - name: bronze_created_at
        description: "Timestamp when record was created in bronze layer"
        data_type: timestamp_ntz
      - name: bronze_updated_at
        description: "Timestamp when record was last updated in bronze layer"
        data_type: timestamp_ntz
      - name: data_quality_status
        description: "Data quality validation status"
        data_type: varchar

  - name: bz_support_tickets
    description: "Bronze layer support tickets data with data quality checks"
    columns:
      - name: TICKET_ID
        description: "Unique identifier for the support ticket"
        data_type: varchar
      - name: USER_ID
        description: "User ID who created the ticket"
        data_type: varchar
      - name: TICKET_TYPE
        description: "Type of support ticket"
        data_type: varchar
      - name: RESOLUTION_STATUS
        description: "Current status of ticket resolution"
        data_type: varchar
      - name: OPEN_DATE
        description: "Date when ticket was opened"
        data_type: date
      - name: LOAD_TIMESTAMP
        description: "Timestamp when record was loaded from source"
        data_type: timestamp_ntz
      - name: UPDATE_TIMESTAMP
        description: "Timestamp when record was last updated in source"
        data_type: timestamp_ntz
      - name: SOURCE_SYSTEM
        description: "Source system identifier"
        data_type: varchar
      - name: bronze_created_at
        description: "Timestamp when record was created in bronze layer"
        data_type: timestamp_ntz
      - name: bronze_updated_at
        description: "Timestamp when record was last updated in bronze layer"
        data_type: timestamp_ntz
      - name: data_quality_status
        description: "Data quality validation status"
        data_type: varchar

  - name: bz_users
    description: "Bronze layer users data with data quality checks"
    columns:
      - name: USER_ID
        description: "Unique identifier for the user"
        data_type: varchar
      - name: USER_NAME
        description: "Display name of the user"
        data_type: varchar
      - name: EMAIL
        description: "Email address of the user"
        data_type: varchar
      - name: COMPANY
        description: "Company name of the user"
        data_type: varchar
      - name: PLAN_TYPE
        description: "Zoom plan type for the user"
        data_type: varchar
      - name: LOAD_TIMESTAMP
        description: "Timestamp when record was loaded from source"
        data_type: timestamp_ntz
      - name: UPDATE_TIMESTAMP
        description: "Timestamp when record was last updated in source"
        data_type: timestamp_ntz
      - name: SOURCE_SYSTEM
        description: "Source system identifier"
        data_type: varchar
      - name: bronze_created_at
        description: "Timestamp when record was created in bronze layer"
        data_type: timestamp_ntz
      - name: bronze_updated_at
        description: "Timestamp when record was last updated in bronze layer"
        data_type: timestamp_ntz
      - name: data_quality_status
        description: "Data quality validation status"
        data_type: varchar

  - name: bz_billing_events
    description: "Bronze layer billing events data with data quality checks"
    columns:
      - name: EVENT_ID
        description: "Unique identifier for the billing event"
        data_type: varchar
      - name: USER_ID
        description: "User ID associated with the billing event"
        data_type: varchar
      - name: EVENT_TYPE
        description: "Type of billing event"
        data_type: varchar
      - name: EVENT_DATE
        description: "Date of the billing event"
        data_type: date
      - name: AMOUNT
        description: "Amount associated with the billing event"
        data_type: number
      - name: LOAD_TIMESTAMP
        description: "Timestamp when record was loaded from source"
        data_type: timestamp_ntz
      - name: UPDATE_TIMESTAMP
        description: "Timestamp when record was last updated in source"
        data_type: timestamp_ntz
      - name: SOURCE_SYSTEM
        description: "Source system identifier"
        data_type: varchar
      - name: bronze_created_at
        description: "Timestamp when record was created in bronze layer"
        data_type: timestamp_ntz
      - name: bronze_updated_at
        description: "Timestamp when record was last updated in bronze layer"
        data_type: timestamp_ntz
      - name: data_quality_status
        description: "Data quality validation status"
        data_type: varchar

  - name: bz_participants
    description: "Bronze layer participants data with data quality checks"
    columns:
      - name: PARTICIPANT_ID
        description: "Unique identifier for the participant"
        data_type: varchar
      - name: MEETING_ID
        description: "Meeting ID the participant joined"
        data_type: varchar
      - name: USER_ID
        description: "User ID of the participant"
        data_type: varchar
      - name: JOIN_TIME
        description: "Timestamp when participant joined"
        data_type: timestamp_ntz
      - name: LEAVE_TIME
        description: "Timestamp when participant left"
        data_type: timestamp_ntz
      - name: LOAD_TIMESTAMP
        description: "Timestamp when record was loaded from source"
        data_type: timestamp_ntz
      - name: UPDATE_TIMESTAMP
        description: "Timestamp when record was last updated in source"
        data_type: timestamp_ntz
      - name: SOURCE_SYSTEM
        description: "Source system identifier"
        data_type: varchar
      - name: bronze_created_at
        description: "Timestamp when record was created in bronze layer"
        data_type: timestamp_ntz
      - name: bronze_updated_at
        description: "Timestamp when record was last updated in bronze layer"
        data_type: timestamp_ntz
      - name: data_quality_status
        description: "Data quality validation status"
        data_type: varchar

  - name: bz_webinars
    description: "Bronze layer webinars data with data quality checks"
    columns:
      - name: WEBINAR_ID
        description: "Unique identifier for the webinar"
        data_type: varchar
      - name: WEBINAR_TOPIC
        description: "Topic or title of the webinar"
        data_type: varchar
      - name: HOST_ID
        description: "Identifier of the webinar host"
        data_type: varchar
      - name: START_TIME
        description: "Webinar start timestamp"
        data_type: timestamp_ntz
      - name: END_TIME
        description: "Webinar end timestamp"
        data_type: timestamp_ntz
      - name: REGISTRANTS
        description: "Number of webinar registrants"
        data_type: number
      - name: LOAD_TIMESTAMP
        description: "Timestamp when record was loaded from source"
        data_type: timestamp_ntz
      - name: UPDATE_TIMESTAMP
        description: "Timestamp when record was last updated in source"
        data_type: timestamp_ntz
      - name: SOURCE_SYSTEM
        description: "Source system identifier"
        data_type: varchar
      - name: bronze_created_at
        description: "Timestamp when record was created in bronze layer"
        data_type: timestamp_ntz
      - name: bronze_updated_at
        description: "Timestamp when record was last updated in bronze layer"
        data_type: timestamp_ntz
      - name: data_quality_status
        description: "Data quality validation status"
        data_type: varchar

  - name: bz_feature_usage
    description: "Bronze layer feature usage data with data quality checks"
    columns:
      - name: USAGE_ID
        description: "Unique identifier for the usage record"
        data_type: varchar
      - name: MEETING_ID
        description: "Meeting ID where feature was used"
        data_type: varchar
      - name: FEATURE_NAME
        description: "Name of the feature used"
        data_type: varchar
      - name: USAGE_DATE
        description: "Date when feature was used"
        data_type: date
      - name: USAGE_COUNT
        description: "Count of feature usage"
        data_type: number
      - name: LOAD_TIMESTAMP
        description: "Timestamp when record was loaded from source"
        data_type: timestamp_ntz
      - name: UPDATE_TIMESTAMP
        description: "Timestamp when record was last updated in source"
        data_type: timestamp_ntz
      - name: SOURCE_SYSTEM
        description: "Source system identifier"
        data_type: varchar
      - name: bronze_created_at
        description: "Timestamp when record was created in bronze layer"
        data_type: timestamp_ntz
      - name: bronze_updated_at
        description: "Timestamp when record was last updated in bronze layer"
        data_type: timestamp_ntz
      - name: data_quality_status
        description: "Data quality validation status"
        data_type: varchar